SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE
FROM EMPLOYEES
ORDER BY 2, 1;

SELECT *
FROM EMPLOYEES
WHERE first_name= 'David' OR first_name = 'Peter';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 50;

SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000;

SELECT *
FROM EMPLOYEES
WHERE SALARY > 15000 OR SALARY < 4000;

SELECT *
FROM EMPLOYEES
WHERE (SALARY > 15000 OR SALARY < 4000 ) AND (DEPARTMENT_ID = 50 OR DEPARTMENT_ID = 80);