SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE <=TO_DATE ('31-DIC-2005') AND HIRE_DATE >= TO_DATE ('01-GEN-2005');

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT > 0;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%' OR FIRST_NAME LIKE '%A%' OR LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%A%';

SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY 1 ASC;

SELECT DISTINCT STREET_ADDRESS
FROM LOCATIONS
WHERE COUNTRY_ID = 'IT';

--SELECT TO_CHAR ( HIRE_DATE, 'dd/mm/yyyy')
--FROM EMPLOYEES
--WHERE ( HIRE_DATE) LIKE '%2005%';