SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID);

SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d USING (DEPARTMENT_ID);

SELECT FIRST_NAME, JOB_TITLE
FROM EMPLOYEES e JOIN JOBS j USING (JOB_ID);

SELECT FIRST_NAME
FROM EMPLOYEES e JOIN JOBS j USING (JOB_ID)
WHERE (SALARY = MIN_SALARY) OR (SALARY = MAX_SALARY);

SELECT FIRST_NAME
FROM EMPLOYEES e JOIN DEPARTMENTS d ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID)
                 JOIN LOCATIONS l ON (d.LOCATION_ID = l.LOCATION_ID);
                 
SELECT DEPARTMENT_NAME, FIRST_NAME ||' '|| LAST_NAME AS MANAGER_NAME
FROM DEPARTMENTS d JOIN EMPLOYEES e ON (d.MANAGER_ID = e.EMPLOYEE_ID);

SELECT DEPARTMENT_NAME, FIRST_NAME ||' '|| LAST_NAME AS MANAGER_NAME
FROM DEPARTMENTS d LEFT OUTER JOIN EMPLOYEES e ON (d.MANAGER_ID = e.EMPLOYEE_ID);

SELECT DEPARTMENT_NAME, FIRST_NAME AS MANAGER_NAME
FROM DEPARTMENTS d LEFT OUTER JOIN EMPLOYEES e ON (d.MANAGER_ID = e.EMPLOYEE_ID);

SELECT DEPARTMENT_NAME, FIRST_NAME ||' '|| LAST_NAME AS MANAGER_NAME
FROM DEPARTMENTS d LEFT OUTER JOIN EMPLOYEES e ON (d.MANAGER_ID = e.EMPLOYEE_ID)
WHERE FIRST_NAME IS NULL;



SELECT e.FIRST_NAME, m.FIRST_NAME ||' '|| m.LAST_NAME AS MANAGER_NAME
FROM EMPLOYEES e JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID);

SELECT e.FIRST_NAME ||' '|| e.LAST_NAME AS NAME, e.MANAGER_ID 
FROM EMPLOYEES e FULL OUTER JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID)
WHERE e.EMPLOYEE_ID NOT IN e.MANAGER_ID;

SELECT DISTINCT e.MANAGER_ID, m.FIRST_NAME ||' '|| m.LAST_NAME AS "NAME"
FROM EMPLOYEES e JOIN EMPLOYEES m ON (e.MANAGER_ID = m.EMPLOYEE_ID);



--FINE SECOND PAGINA


SELECT DEPARTMENT_NAME, FIRST_NAME ||''|| LAST_NAME AS MANAGER_NAME
FROM DEPARTMENTS d LEFT OUTER JOIN EMPLOYEES e ON (d.MANAGER_ID = e.EMPLOYEE_ID);

SELECT TO_CHAR(HIRE_DATE, 'DD-MM-YYYY')
FROM EMPLOYEES
WHERE 1 LIKE '%1%';

SELECT *
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'DD-MM-YYYY') LIKE '%2005%';

SELECT *
FROM NLS_SESSION_PARAMETERS;