SELECT
	SALARY,
	SALARY*1.085,
	SALARY*0.085
FROM
	EMPLOYEES;

SELECT
	FIRST_NAME,
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	REGEXP_LIKE (FIRST_NAME,'a','i') OR REGEXP_LIKE(LAST_NAME,'a','i');
	
SELECT MONTHS_BETWEEN(SYSDATE, HIRE_DATE)
FROM EMPLOYEES;

SELECT LPAD('*',FLOOR(SALARY/1000),'*')
FROM EMPLOYEES;

SELECT NVL2(COMMISSION_PCT,TO_CHAR(COMMISSION_PCT,'0D99'),'no value')
FROM EMPLOYEES;