SELECT MAX (SALARY), MIN(SALARY), SUM (SALARY), AVG (SALARY)
FROM EMPLOYEES;

SELECT JOB_ID, MAX (SALARY), MIN(SALARY), SUM (SALARY), AVG (SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT COUNT(*)
FROM (SELECT DISTINCT MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL );

SELECT MAX(SALARY)-MIN(SALARY)
FROM EMPLOYEES;

SELECT DISTINCT DIFFERENCE
FROM (SELECT JOB_ID, MAX(SALARY)-MIN(SALARY) AS difference
FROM EMPLOYEES
GROUP BY job_id);

SELECT MIN(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING (MANAGER_ID IS NOT NULL) AND (MIN(SALARY) >= 6000);
