SELECT MAX (SALARY), MIN(SALARY), SUM (SALARY), AVG (SALARY)
FROM EMPLOYEES;

SELECT JOB_ID, MAX (SALARY), MIN(SALARY), SUM (SALARY), AVG (SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT COUNT(IT_PROG)
FROM EMPLOYEES NATURAL JOIN (SELECT JOB_ID, COUNT(EMPLOYEE_ID)
                             FROM EMPLOYEES
                             GROUP BY JOB_ID)
WHERE;